GET http://localhost:8080/courses

###

GET http://localhost:8080/courses/1

###

POST http://localhost:8080/courses
Content-Type: application/json

{
    "name": "Java",
    "link": "https://www.java.com"
}

###

PUT http://localhost:8080/courses/2
Content-Type: application/json

{
    "name": "Atualizado Java"
}

###

DELETE http://localhost:8080/courses/1

###